// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-kifS4rGb-v2UssU342g8MeTF_VOyxCQ',
    appId: '1:742220755518:web:7cddb7713c0798972a576f',
    messagingSenderId: '742220755518',
    projectId: 'portfolio-web-ustar-b7be6',
    authDomain: 'portfolio-web-ustar-b7be6.firebaseapp.com',
    storageBucket: 'portfolio-web-ustar-b7be6.firebasestorage.app',
    measurementId: 'G-5DK668BR8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAvQHL4zzGbWYMRW8fAN5qR9V8LYlycWc',
    appId: '1:742220755518:android:b2259c359cdee1362a576f',
    messagingSenderId: '742220755518',
    projectId: 'portfolio-web-ustar-b7be6',
    storageBucket: 'portfolio-web-ustar-b7be6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBwv5DYgP_j99jS68mIiqrZDYSQEFF8II',
    appId: '1:742220755518:ios:ab6a82dbd16af3592a576f',
    messagingSenderId: '742220755518',
    projectId: 'portfolio-web-ustar-b7be6',
    storageBucket: 'portfolio-web-ustar-b7be6.firebasestorage.app',
    iosBundleId: 'com.example.mywebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBwv5DYgP_j99jS68mIiqrZDYSQEFF8II',
    appId: '1:742220755518:ios:ab6a82dbd16af3592a576f',
    messagingSenderId: '742220755518',
    projectId: 'portfolio-web-ustar-b7be6',
    storageBucket: 'portfolio-web-ustar-b7be6.firebasestorage.app',
    iosBundleId: 'com.example.mywebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-kifS4rGb-v2UssU342g8MeTF_VOyxCQ',
    appId: '1:742220755518:web:80e373dd015f5cf92a576f',
    messagingSenderId: '742220755518',
    projectId: 'portfolio-web-ustar-b7be6',
    authDomain: 'portfolio-web-ustar-b7be6.firebaseapp.com',
    storageBucket: 'portfolio-web-ustar-b7be6.firebasestorage.app',
    measurementId: 'G-3CKHPWPX9V',
  );
}
